### ISSUE TITLE
The fonts are mismatched for different languages

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#116]
**Describe the bug**

**To Reproduce**
1. Go to website
2. Click on the language selector
3. Observe mismatched font styles

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/132857766-2564543e-92bf-4844-ad1c-7a133b481d27.png)
should look more like this
![image](https://user-images.githubusercontent.com/2031472/132857975-329597be-78e7-4c34-a24b-55ec731999a0.png)

**Comment by dialectrical** [comment]
I took a look at this and it looks like there were two problems. First, Work Sans doesn't seem to handle Cyrillic, so `LanguageSelect.tsx` goes looking for the next font, and when it looks in `VaxxTheme.js` it goes straight to sans-serif, rather than something like Roboto that does handle Cyrillic.

I added the font stack from `index.css` ("Work Sans", -apple-system, BlinkMacSystemFont, "Segoe UI",
    "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans",
    "Helvetica Neue", sans-serif) to `VaxxTheme.js` to attempt a fix!
    
    I'll submit a pull request.

**Comment by noway** [comment]
Awesome, solved! Thanks to @dialectrical for figuring it out 💯
