### ISSUE TITLE
"Public Holidays" for Life Pharmacy St Lukes is cut-off

### ISSUE THREAD

**Issue by noway** [CovidEngine/vaxxnz#130]
**Describe the bug**
"Public Holidays" text for Life Pharmacy St Lukes is cut-off

**To Reproduce**
1. Go to website
2. Find Life Pharmacy St Lukes in Open Today
3. Observe Public Holidays

**Screenshots**
![image](https://user-images.githubusercontent.com/2031472/132931323-8210c419-7e3c-402d-a925-286552d5f263.png)
![image](https://user-images.githubusercontent.com/2031472/132931319-8b96dc04-59ac-47f1-85bf-a41221022468.png)

**Additional context**
Props to @geeksteph for spotting this.
Might be a data issue...

**Comment by rquitales** [comment]
Looks like a simple fix within the vaxxnzlocations repo.
Just need to handle the [colon string splitting logic](https://github.com/CovidEngine/vaxxnzlocations/blob/43b0a852c9724efd273a158cc05749ebdfbaca48/healthpointLocationsOpenNow.ts#L142).

This entry contains multiple colons within the text data, and we only want to split on the first colon. Since the first colon has a space padding after it (eg. "Public Holidays: blah blah blah..."), we can switch the logic to split on `": "` instead of `":"`. The remaining colons present are associated to times, so they won't be split on as they don't have a space following them.

Will send through a PR for this in the other repo.

**Comment by noway** [comment]
This should be fixed next time cron job is run 🙏🏻  (i tested it, i hope it works in prod)

**Comment by rquitales** [comment]
@noway Looks like we can close this issue now!
